stolostron/insights-client

README.md

Fix Readme repo name

---

pkg/retriever/reportretriever.go
pkg/retriever/reportretriver_test.go
pkg/types/types.go

 updated types to get CRC json

---

main.go
pkg/retriever/reportretriever.go

 fixed comments per pr review

---

main.go
pkg/monitor/clustermonitor.go
pkg/monitor/clustermonitor_test.go
pkg/retriever/reportretriever.go
pkg/retriever/reportretriever_test.go

**Related Issue:**  open-cluster-management/backlog#8621

Use managed cluster list to retrieve Insight reports

---

pkg/retriever/reportretriever.go

added content length log message

---

go.mod
go.sum
pkg/config/kubeClient.go
pkg/processor/reportprocessor.go

 migrated policyreport to v1alpha2

---

main.go
pkg/handlers/healthProbes.go
pkg/monitor/clustermonitor.go
pkg/processor/reportprocessor.go
pkg/retriever/reportretriever.go

updated health probes

---

main.go
pkg/monitor/clustermonitor.go
pkg/monitor/clustermonitor_test.go
pkg/retriever/contentretriever_test.go
pkg/retriever/reportretriever.go
pkg/retriever/reportretriever_test.go

 refresh token before every report fetch

---

pkg/types/policyReportTypes.go

 fixed details object type

---

main.go
pkg/config/config.go
pkg/processor/reportprocessor.go
pkg/retriever/contentretriever.go
pkg/retriever/contentretriever_test.go
pkg/retriever/reportretriever.go
pkg/retriever/reportretriever_test.go
pkg/types/policyReportTypes.go

This is a test PR `/hold` /hold

 added option to test with qa system

---

pkg/monitor/clustermonitor.go
pkg/monitor/clustermonitor_test.go
test-data/managed-cluster.json

use clusterversions for getting hub cluster id

---

main.go
pkg/config/kubeClient.go
pkg/processor/reportprocessor.go
pkg/types/policyReportTypes.go

**Related Issue:**  open-cluster-management/backlog#11701

Only create one PolicyReport per cluster

---

pkg/config/config.go
pkg/retriever/reportretriever.go

Add a pause between cluster report requests

---

main.go
pkg/processor/reportprocessor.go
pkg/types/contentTypes.go
pkg/types/policyReportTypes.go

- Delete PR if it has no rules
- if rule is resolved -> remove it from the PR
- Dont use skips (skip != resolved)
- dont create PR if no violations
/hold

Update lifecycle of PolicyReport resource

---

pkg/retriever/reportretriever.go
pkg/types/policyReportTypes.go

Fix type for response body errors array

---

pkg/processor/reportprocessor.go

**Related Issue:**  open-cluster-management/backlog#11810
- filter the tutorial insight as it is unnecessary for the user.

Add check to filter out the tutorial insight

---

pkg/processor/reportprocessor.go

https://github.com/open-cluster-management/backlog/issues/12669
- Add cluster info to scope in PolicyReport resources

Add scope to PolicyReport resource

---

pkg/processor/reportprocessor.go
pkg/processor/reportprocessor_test.go

Add the `-policyreport` suffix to all policyreport names

Add the -policyreport suffix to all policyreport names

---

pkg/processor/reportprocessor.go

include extra data for templates

---

pkg/processor/reportprocessor.go
pkg/retriever/contentretriever.go

remove confusing log

---

pkg/processor/reportprocessor.go
pkg/retriever/reportretriever.go

Add extra logging for healthy cluster check and debugging

---

pkg/monitor/clustermonitor.go

Dont update local-cluster using ManagedCluster

---

pkg/processor/reportprocessor.go
pkg/types/contentTypes.go

Include total_risk score from content data

---

pkg/processor/reportprocessor.go

- Use the correct field to filter out the tutorial insights rule

Filter the tutorial rule correctly

---

Dockerfile

**Related Issue:**  open-cluster-management/backlog/issues/13277
- Update base docker image to UBI 8.4

Update base docker image to UBI 8.4

---

pkg/retriever/contentretriever.go
pkg/retriever/contentretriever_test.go
pkg/retriever/reportretriever.go
pkg/retriever/reportretriever_test.go

 updated to acm header

---

pkg/monitor/clustermonitor.go
pkg/retriever/reportretriever.go

 resolved race condition

---

pkg/retriever/contentretriever.go

Create content configmap only if there are contents

---

.travis.yml

**Related Issue:**  open-cluster-management/backlog#10511
Remove sonar and fast forward from build

Remove sonar and fast forward from build

---

Makefile.prow

Signed-off-by: mqhackett <mahacket@redhat.com>
**Related Issue:**  open-cluster-management/backlog#10511
Add make target for lint in prow

add make target for lint

---

pkg/processor/reportprocessor.go
pkg/processor/reportprocessor_test.go

**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/14725
adds violations on grc policies to the policyreport results field

Add governance violations to results in policyReports

---

README.md

**Related Issue:**  open-cluster-management/backlog#15265
Image rebuild

[release 2.3] image rebuild 

---

Makefile.prow

**Related Issue:**  open-cluster-management/backlog#10511

Included e2e test in prow

---

pkg/types/contentTypes.go
test-data/content.json

**Related Issue:**  open-cluster-management/backlog#17336
https://github.com/open-cluster-management/backlog/issues/17336

[release-2.3] fixed Impact to integer per contents api

---

pkg/types/contentTypes.go
test-data/content.json

**Related Issue:**  open-cluster-management/backlog#17336
https://github.com/open-cluster-management/backlog/issues/17336

Make Impact as int to reflect CCX service API

---

Dockerfile
go.mod
go.sum

**Related Issue:**  open-cluster-management/backlog#15570

update to go 1.17

---

Dockerfile
go.mod
go.sum

**Related Issue:**  open-cluster-management/backlog#15570

[release 2.4] update 2.4 to go 1.17

---

.travis.yml
Dockerfile
go.mod

**Related Issue:**  open-cluster-management/backlog#15572

[release 2.3] update 2.3 to go 1.17

---

Dockerfile
Makefile
build/run-e2e-tests.sh
go.mod
go.sum
main.go
pkg/monitor/clustermonitor.go
pkg/monitor/clustermonitor_test.go
pkg/processor/reportprocessor.go
pkg/processor/reportprocessor_test.go
pkg/retriever/contentretriever.go
pkg/retriever/contentretriever_test.go
pkg/retriever/reportretriever.go
pkg/retriever/reportretriever_test.go

**Related Issue:**  open-cluster-management/backlog#18729 and https://github.com/stolostron/backlog/issues/18862

[release 2.4] update org references to stolostron

---

pkg/retriever/reportretriever.go

**Related Issue:**  https://github.com/stolostron/backlog/issues/19407#issuecomment-1088614412
fixes issue where if a cluster eligible for CCX errors when getting insights, it wouldn't generate policyreport violations for GRC either

ccx cluster error fix

---

pkg/retriever/reportretriever.go

**Related Issue:**  [open-cluster-management/backlog#<ISSUE_NUMBER>
](https://github.com/stolostron/backlog/issues/19407)

 fixed return to not to exit the loop

---

pkg/monitor/clustermonitor.go

check if cluster is already present before add

---

.github/pull_request_template.md
.github/workflows/stale.yml

Signed-off-by: dislbenn <dbennett@redhat.com>
**Related Issue:**  stolostron/backlog#22054
Added stale script automation to help manage and reduce inactive prs.

Added issue/pr stale workload automation

---

pkg/monitor/clustermonitor.go

backport of fixes for https://github.com/stolostron/backlog/issues/21707

Managed cluster auto pickup

---

README.md

Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  stolostron/backlog#22455
No-op pr to trigger rebuild for image scan issue.

No-op PR for rebuild

---

README.md

**Related Issue:**  https://github.com/stolostron/backlog/issues/22455

Dummy PR to get the latest tag published

---

pkg/monitor/clustermonitor.go

**Related Issue:** https://github.com/stolostron/backlog/issues/22531

do not remove local-cluster from cluster list even if it is detached

---

Dockerfile
go.mod

**Related Issue:**  https://github.com/stolostron/backlog/issues/24212

[2.5] Update to golang 1.18

---

README.md

Signed-off-by: Jorge Padilla <jpadilla@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/25337
- Rebuild to pickup latest image.

Trigger prow rebuild 2022-09-16

---

pkg/processor/reportprocessor.go

ref: https://issues.redhat.com/browse/ACM-7264
Followup to:
- #143

Fix for when compliance status is nil

---

pkg/processor/reportprocessor.go

The name from the status was used, but when a policy has policy-templates of different kinds with the same name, only the severity from the first policy-template is returned and is used for all policy-templates with that name.
ref: https://issues.redhat.com/browse/ACM-6350

Use index from status for policy-templates

---

pkg/processor/reportprocessor.go

**Related Issues:**
- https://issues.redhat.com/browse/ACM-6350
- https://issues.redhat.com/browse/ACM-7264
Replaces:
- #145 
Cherry-picks:
- #143 
- #150 
- #152 
- #153

[release-2.8] Manual cherry-pick to handle non-OCM policy types (#143, #150)

---

pkg/processor/reportprocessor.go

**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>
Updating the PolicyReport was done via Patch. This changes the logic to use Update so there are no conflicts with new schema fields.

Use Update not Patch for PolicyReport updates

---

README.md
test-data/e2e/insights-chart/templates/insights-deployment.yaml

**Related Issue:**  [ACM-14651](https://issues.redhat.com/browse/ACM-14651)

Update insights-results-aggregator API to v2

---

renovate.json

- Update konflux renovate schedule

Update konflux renovate schedule

---

OWNERS

add smcavey to owners 2.12

---

OWNERS

add smcavey to owners 2.10

---

OWNERS

add smcavey 2.11 owners

---

go.mod

bump golang.org/x/net version to mitigate cves

update golang net for cves

---

README.md

**Related Issue:**  https://redhat-internal.slack.com/archives/C04L50S5XM4/p1738091780182129

[release-2.10] No-op to re-publish image

---

.tekton/insights-client-acm-210-pull-request.yaml
.tekton/insights-client-acm-210-push.yaml

**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config

[release-2.10] Update Konflux config

---

main.go
pkg/config/config.go
pkg/config/kubeClient_test.go
pkg/retriever/reportretriever_test.go

Calling `glog` before `flag.Parse()` is problematic.

Fix config setup

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod
go.sum

Manual cherry-pick of https://github.com/stolostron/insights-client/pull/304

release-2.13 Update to go 123

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod
go.sum

Manual cherry-pick of https://github.com/stolostron/insights-client/pull/304

release-2.12 Update to go 123 release 2.12

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod
go.sum

Update go to 1.23 and add .ci-operator.yaml file

[release-2.11] update go 123

---

.ci-operator.yaml
Dockerfile
Makefile
Makefile.prow
go.mod
go.sum

Added .ci-operator.yaml and updated go to 1.23

[release-2.9] update go to 1.23

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod
go.sum

Updated Go to 1.23
Added .ci-operator.yaml file

[release-2.10] update go 1.23

---

go.mod
go.sum

[release-2.9] fix cve-2025-22868/22869

---

.tekton/insights-client-acm-214-pull-request.yaml
.tekton/insights-client-acm-214-push.yaml
Dockerfile
Dockerfile.rhtap
renovate.json

N/A
- [Enabling hermetic builds in Konflux](https://konflux.pages.redhat.com/docs/users/building/hermetic-builds.html)
- [Prefetching package manager dependencies for hermetic builds](https://konflux.pages.redhat.com/docs/users/building/prefetching-dependencies.html)
- Updates renovate.json

Enable konflux hermetic builds

---

.tekton/insights-client-acm-213-pull-request.yaml
.tekton/insights-client-acm-213-push.yaml
Dockerfile
Dockerfile.rhtap

Manual cherry pick of https://github.com/stolostron/insights-client/pull/375 and https://github.com/stolostron/insights-client/pull/376

[release-2.13] enable hermetic builds

---

.github/pull_request_template.md
.github/renovate.json

**Related Issue:**  N/A
- Move renovate.json and update package grouping
- Update PR template

Move renovate.json and update package grouping

---

.tekton/insights-client-acm-211-pull-request.yaml

- Added image-digest and image-url params to fix https://github.com/stolostron/insights-client/pull/415

[release-2.11] fix sast-snyk-check

---

.tekton/insights-client-acm-214-pull-request.yaml

- Added image-digest param to fix https://github.com/stolostron/insights-client/pull/412

fix sast-coverity-check-oci-ta add image-digest

---

.tekton/insights-client-acm-210-pull-request.yaml

- Added image-digest and image-url params to fix https://github.com/stolostron/insights-client/pull/414

[release-2.10] fix sast-snyk-check

---

.tekton/insights-client-acm-210-pull-request.yaml

- moved params according to https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8

[release-2.10] fix sast-snyk-check params

---

.tekton/insights-client-acm-214-push.yaml

https://issues.redhat.com/browse/ACM-0000
- Added ...

fix konflux on push config

---

.tekton/insights-client-acm-211-push.yaml

https://issues.redhat.com/browse/ACM-0000
- Added ...

[release-2.11] fix konflux on push config

---

.tekton/insights-client-acm-214-pull-request.yaml
.tekton/insights-client-acm-214-push.yaml

Konflux PR #380 was accidentally merged to `release-2.14`.  Merging back into `main`.

[main] Update Konflux references (#380)

---

go.mod
go.sum

security updates to be in line with main

[release-2.10] security updates

---

.tekton/insights-client-acm-214-pull-request.yaml

N/A
- [release-2.14] Update konflux to run on PRs to release-2.14

[release-2.14] Update konflux to run on PRs to release-2.14

---

.tekton/insights-client-acm-213-push.yaml

[release-2.13] multi-arch builds

---

.tekton/insights-client-acm-215-pull-request.yaml
.tekton/insights-client-acm-215-push.yaml

- Added hermetic, multi-arch, other missing params

[main] hermetic, multiarch, other params

---

.tekton/insights-client-acm-212-pull-request.yaml
.tekton/insights-client-acm-212-push.yaml
Dockerfile
Dockerfile.rhtap

- Added multi arch and hermetic builds

[release-2.12] multi arch hermetic builds

---

.tekton/insights-client-acm-211-pull-request.yaml
.tekton/insights-client-acm-211-push.yaml
Dockerfile
Dockerfile.rhtap

- Added multi arch and hermetic builds

[release-2.11] multi arch and hermetic builds

---

.tekton/insights-client-acm-211-push.yaml

[release-2.11] multi-arch builds

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

[release-2.10] update go to 1.24 (#588)
