stolostron/insights-client

- pkg/monitor/clustermonitor.go
**Related Issue:**  open-cluster-management/backlog#8621
- Include managed cluster IDs after they are upgraded to 4.X
> Include managed cluster IDs after they are upgraded to 4.X

- README.md
- generate_qaprodauth_cert.sh
- pkg/config/config.go
- pkg/monitor/clustermonitor.go
- pkg/processor/reportprocessor.go
- pkg/retriever/contentretriever.go
- pkg/retriever/reportretriever.go
- pkg/types/policyReportTypes.go
**Related Issue:**  open-cluster-management/backlog#12202
Add handling for an env var `CACert` that will enable communication with qaprodauth for dev and testing.
`/hold` /hold
> Add ability to set ca cert to use qaprodauth

- main.go
- pkg/config/config.go
- pkg/processor/reportprocessor.go
- pkg/retriever/contentretriever.go
- pkg/retriever/contentretriever_test.go
- pkg/retriever/reportretriever.go
- pkg/retriever/reportretriever_test.go
**Related Issue:**  open-cluster-management/backlog#11809
- Add logic to create a configmap `insight-content-data`, to store all insight content data
> Create a configmap to store all insight content data

- pkg/processor/reportprocessor.go
- pkg/processor/reportprocessor_test.go
- Openshift category label on policy violations is redundant. Adds a func to filter it out.
> Filter the openshift category label

- pkg/processor/reportprocessor.go
**Related Issue:**  open-cluster-management/backlog#13900
- We will keep the `summary.fail` count up to date with the total number of violations on a cluster so the cli response will display total count as seen below:
> Update the summary.fail count with total count of violations

- pkg/processor/reportprocessor.go
**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/17260
Previously the client would not delete a policyreport if there were GRC violations in the existing policyreport, but it would also not update the policyreport unless new violations were found. This led to some weird scenarios where if a GRC violation was the only violation in the policyreport, it would continue to show up even after being remediated until another violation was reported.
> delete policyreport when there are no grc or insights violations

- pkg/processor/reportprocessor.go
**Related Issue:**  https://github.com/stolostron/backlog/issues/19496
currently, if a GRC policy has a severity with the first letter capitalized, total_risk will not be calculated properly. this change fixes the issue.
> convert grc severity to lowercase to avoid processing issues

- pkg/processor/reportprocessor.go
**Related Issue:**  https://github.com/stolostron/backlog/issues/19496
converts grc policy severity to lower case to avoid mapping issues if a user capitalizes the first letter of the severity
> convert grc sev to lower case

- main.go
- pkg/monitor/clustermonitor.go
- pkg/monitor/clustermonitor_test.go
- pkg/retriever/reportretriever.go
- test-data/managed-cluster-nonopenshift.json
**Related Issue:**  https://github.com/stolostron/backlog/issues/19407
Processes GRC violations for non-openshift clusters and restricts insights to the same cluster constraints as before. Making this fix in insights-client for 2.4 to help resolve the issue quickly, but I will be investigating https://github.com/stolostron/backlog/issues/19753 for the fix in 2.5.
> process grc violations on non-openshift clusters

- pkg/monitor/clustermonitor.go
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=2075440
@willkutler  it appears that a timing issue , that when the add even happens the cluster id is empty . That causes to miss the cluster when it joins the hub. Made a fix , if we get a managedcluster CR update and we dont know about it , add to the list.
>  added cluster if its not added by add event

- main.go
- pkg/monitor/clustermonitor.go
- pkg/retriever/reportretriever.go
**Related Issue:**  https://github.com/stolostron/backlog/issues/21751
Currently the `retriever.NewRetriever()` function will error if the call to the CCX server fails, so running the client on a disconnected environment will cause no policyreports to be generated for GRC violations. This makes it so that if that call fails, we still process GRC violations and produce violations for them.
> Process GRC violations on disconnected env

- pkg/monitor/clustermonitor.go
**Related Issue:**  https://github.com/stolostron/backlog/issues/22531
fixes an issue where local-cluster's policyreport would get removed forever if it was detached
> backport persist local cluster fix

- pkg/monitor/clustermonitor.go
When a cluster is missing its id.k8s.io cluster claim, it can't be handled. There was no indication that this was happening except a debug log message that is not displayed by default. This commit makes the log message clearer and changes it to a regular info log.
Relates:
https://issues.redhat.com/browse/ACM-2625
> Provide a clear log message when a cluster can't be handled

- pkg/processor/reportprocessor.go
When a non-OCM policy is in play (i.e. Gatekeeper), it doesn't have a severity field, so the insights client was panicking.
ref: https://issues.redhat.com/browse/ACM-6350
> Go upgrade / Handle non-OCM policy types

- pkg/processor/reportprocessor.go
ref: https://issues.redhat.com/browse/ACM-6350
Followup to:
- #143 
The previous PR was checking for the annotation on the root policy, which would set the severity on every policy template. The intention was to be able to set the severity on each policy template.
> Check severity on template, not root policy

- pkg/processor/reportprocessor.go
Currently the timestamp in the PolicyReport is the time the report was filed. It'd make more sense to use the timestamp from the template's history.
Refs:
- https://issues.redhat.com/browse/ACM-6921
**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>
> Update PolicyReport to use template timestamp

- pkg/processor/reportprocessor_test.go
Most of the code related to parsing the ACM policies in
reportprocessor.go was not covered by tests. This adds a test to handle
some common code paths.
Relates:
https://issues.redhat.com/browse/ACM-7401
> Add test coverage to parsing the cluster's ACM policies

- pkg/monitor/clustermonitor.go
**Related Issue:**  stolostron/backlog#<ISSUE_NUMBER>
Previously the cluster vendor was obtained from ManagedCluster.status.clusterclaims["product.open-cluster-management.io"]
This changes the logic to get vendor from ManagedCluster.labels["vendor"]
> use ManagedCluster label to get cluster vendor more reliably

- go.mod
bump golang.org/x/net to v0.33.0 for cve mitigation
> update golang net for cves

- .tekton/insights-client-acm-214-pull-request.yaml
- moved image-digest param according to https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8
> fix sast-coverity-check-oci-ta params

- go.mod
- go.sum
bump google.golang.org/protobuf version used by other repos for security
> main security updates

- Dockerfile.rhtap
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
> chore(KONFLUX-6210): fix and set name and cpe label for insights-client-acm-214
